;/*FB_PKG_DELIM*/

__d("MWTextPairing.react",["MDSTextPairing.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){return h.jsx(c("MDSTextPairing.react"),babelHelpers["extends"]({},a))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("XCometRestrictedAccountsControllerRouteBuilder",["jsExtraRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsExtraRouteBuilder")("/messages/restricted/t/{thread_key}/",Object.freeze({}),["/messages/restricted/"],void 0);b=a;g["default"]=b}),98);
__d("XMessengerDotComCometRestrictedAccountsControllerRouteBuilder",["jsExtraRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsExtraRouteBuilder")("/restricted/t/{thread_key}/",Object.freeze({}),["/restricted/"],void 0);b=a;g["default"]=b}),98);
__d("MWInboxRestrictedAccountsRouteBuilder.bs",["CurrentEnvironment","XCometRestrictedAccountsControllerRouteBuilder","XMessengerDotComCometRestrictedAccountsControllerRouteBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=c("CurrentEnvironment").facebookdotcom?{buildURL:function(a){return c("XCometRestrictedAccountsControllerRouteBuilder").buildURL(a)},buildURLWithoutThread:function(a){return c("XCometRestrictedAccountsControllerRouteBuilder").buildExtraURL("/messages/restricted/",a)}}:{buildURL:function(a){return c("XMessengerDotComCometRestrictedAccountsControllerRouteBuilder").buildURL(a)},buildURLWithoutThread:function(a){return c("XMessengerDotComCometRestrictedAccountsControllerRouteBuilder").buildExtraURL("/restricted/",a)}};b=a.buildURL;d=a.buildURLWithoutThread;g.routeBuilderModule=a;g.buildURL=b;g.buildURLWithoutThread=d}),98);
__d("LSPlatformLogout.bs",["LSCookie.bs","Promise","Promise.bs","QPLUserFlow","cr:3571","qpl","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function i(a){if(b("cr:3571")==null)return b("Promise").resolve();else{c("QPLUserFlow").start(c("qpl")._(25311266,"236"),{cancelOnUnload:!0,timeoutInMs:3e3});return d("Promise.bs").$$catch(b("Promise").all([b("cr:3571").deleteDB(),d("LSCookie.bs").deleteCookie()]).then(function(a){c("QPLUserFlow").endSuccess(c("qpl")._(25311266,"236"));return b("Promise").resolve()}),function(a){c("QPLUserFlow").endFailure(c("qpl")._(25311266,"236"),"fail");return b("Promise").resolve()})}}function a(a){return h.useCallback(i,[])}g.LSPersistedDatabaseProvider=b("cr:3571");g.logout=i;g.useHook=a}),98);
__d("MessengerWellbeingRestrictFailedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("474");c=b("FalcoLoggerInternal").create("messenger_wellbeing_restrict_failed",a);e.exports=c}),null);
__d("MessengerWellbeingRestrictFailedFalcoEvent.bs",["MessengerWellbeingRestrictFailedFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingRestrictFailedFalcoEvent").log(a)}function c(a){b("MessengerWellbeingRestrictFailedFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingRestrictFailedFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingRestrictFailedFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingRestrictSucceededFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("480");c=b("FalcoLoggerInternal").create("messenger_wellbeing_restrict_succeeded",a);e.exports=c}),null);
__d("MessengerWellbeingRestrictSucceededFalcoEvent.bs",["MessengerWellbeingRestrictSucceededFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingRestrictSucceededFalcoEvent").log(a)}function c(a){b("MessengerWellbeingRestrictSucceededFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingRestrictSucceededFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingRestrictSucceededFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingRestrictTappedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("481");c=b("FalcoLoggerInternal").create("messenger_wellbeing_restrict_tapped",a);e.exports=c}),null);
__d("MessengerWellbeingRestrictTappedFalcoEvent.bs",["MessengerWellbeingRestrictTappedFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingRestrictTappedFalcoEvent").log(a)}function c(a){b("MessengerWellbeingRestrictTappedFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingRestrictTappedFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingRestrictTappedFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingUnrestrictFailedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("482");c=b("FalcoLoggerInternal").create("messenger_wellbeing_unrestrict_failed",a);e.exports=c}),null);
__d("MessengerWellbeingUnrestrictFailedFalcoEvent.bs",["MessengerWellbeingUnrestrictFailedFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingUnrestrictFailedFalcoEvent").log(a)}function c(a){b("MessengerWellbeingUnrestrictFailedFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingUnrestrictFailedFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingUnrestrictFailedFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingUnrestrictSucceededFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("483");c=b("FalcoLoggerInternal").create("messenger_wellbeing_unrestrict_succeeded",a);e.exports=c}),null);
__d("MessengerWellbeingUnrestrictSucceededFalcoEvent.bs",["MessengerWellbeingUnrestrictSucceededFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingUnrestrictSucceededFalcoEvent").log(a)}function c(a){b("MessengerWellbeingUnrestrictSucceededFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingUnrestrictSucceededFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingUnrestrictSucceededFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("MessengerWellbeingUnrestrictTappedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("484");c=b("FalcoLoggerInternal").create("messenger_wellbeing_unrestrict_tapped",a);e.exports=c}),null);
__d("MessengerWellbeingUnrestrictTappedFalcoEvent.bs",["MessengerWellbeingUnrestrictTappedFalcoEvent"],(function(a,b,c,d,e,f){"use strict";function a(a){b("MessengerWellbeingUnrestrictTappedFalcoEvent").log(a)}function c(a){b("MessengerWellbeingUnrestrictTappedFalcoEvent").logAsync(a)}function d(a){b("MessengerWellbeingUnrestrictTappedFalcoEvent").logImmediately(a)}function e(a){b("MessengerWellbeingUnrestrictTappedFalcoEvent").logCritical(a)}f.log=a;f.logAsync=c;f.logImmediately=d;f.logCritical=e}),null);
__d("LsMessageRequestsEntryPoint.bs",["bs_caml_int64"],(function(a,b,c,d,e,f){"use strict";a=b("bs_caml_int64").zero;c=b("bs_caml_int64").one;d=[0,2];e=[0,3];b=[0,4];var g=[0,5];f.settings=a;f.pendingRequests=c;f.notifications=d;f.chatTabSettings=e;f.chatTabPendingRequests=b;f.inboxFolderList=g}),null);